# GA4 Ecommerce Funnel Data Prep

Evelina Ramoskaite

### Extraction

In [2]:
# Import libraries
from google.cloud import bigquery # reference readme file for setup/authentication instructions
import pandas as pd

In [3]:
# Specifying Project ID 
PROJECT_ID = 'bigquery-public-evelinar'
client = bigquery.Client(project=PROJECT_ID)

In [4]:
# Set Start and End Date
# Format: YYYYMMDD
START_DATE = '20210101'
END_DATE = '20210131'

In [5]:
# Extracting data from Bigquery 
with open('checkout_funnel_daily.sql') as f:
     query = f.read().format(start_date=START_DATE, end_date=END_DATE)
df = client.query(query).to_dataframe()

In [261]:
print(df.shape)
df.head(40)

(238073, 12)

,event_date,event_name,user_pseudo_id,session_id,event_ts,country,state,device_category,traffic_medium,traffic_source,transaction_id,revenue
0,20210124,session_start,1008607.7032882869,521445891,2021-01-24 10:19:49.218426+00:00,United States,Ohio,mobile,organic,google,NaN,NaN
1,20210124,view_item,1027865.2921216251,6122537537,2021-01-24 20:47:05.204087+00:00,United States,Pennsylvania,mobile,organic,google,(not set),NaN
2,20210124,session_start,1027865.2921216251,6122537537,2021-01-24 20:43:56.274718+00:00,United States,Pennsylvania,mobile,organic,google,NaN,NaN
3,20210124,session_start,1027865.2921216251,8887175570,2021-01-24 22:39:01.029399+00:00,United States,Pennsylvania,mobile,referral,shop.googlemerchandisestore.com,NaN,NaN
4,20210124,session_start,1043145.0716229192,7515384017,2021-01-24 23:58:49.575521+00:00,United States,Virginia,mobile,organic,google,NaN,NaN
5,20210124,session_start,1044510.5873644104,6078712742,2021-01-24 18:14:07.911914+00:00,United States,Florida,desktop,(none),(direct),NaN,NaN
6,20210124,session_start,1048584.7594502159,9109808764,2021-01-24 13:34:14.674744+00:00,Sweden,Vastra Gotaland County,desktop,<Other>,<Other>,NaN,NaN
7,20210124,view_item,1080463.7425293909,612924697,2021-01-24 12:12:24.028087+00:00,United States,Connecticut,desktop,(none),(direct),(not set),NaN
8,20210124,session_start,1080463.7425293909,612924697,2021-01-24 12:10:18.088711+00:00,United States,Connecticut,desktop,(none),(direct),NaN,NaN
9,20210124,add_shipping_info,1080463.7425293909,612924697,2021-01-24 12:15:40.226652+00:00,United States,Connecticut,desktop,(none),(direct),(not set),NaN
10,20210124,view_item,1080463.7425293909,612924697,2021-01-24 12:11:05.049487+00:00,United States,Connecticut,desktop,(none),(direct),(not set),NaN
11,20210124,session_start,1081243.2845262420,508074986,2021-01-24 16:02:23.106950+00:00,United States,Mississippi,desktop,cpc,google,NaN,NaN
12,20210124,session_start,1096204.3430350292,6564790103,2021-01-24 10:13:57.285898+00:00,United States,Florida,mobile,<Other>,<Other>,NaN,NaN
13,20210124,session_start,1104044.8966887599,9200759003,2021-01-24 11:00:51.020512+00:00,Spain,Catalonia,desktop,organic,google,NaN,NaN
14,20210124,session_start,1107790.9699810589,8702543339,2021-01-24 20:09:55.940965+00:00,United States,South Carolina,desktop,(none),(direct),NaN,NaN
15,20210124,view_item,1107790.9699810589,8702543339,2021-01-24 20:10:04.023755+00:00,United States,South Carolina,desktop,(none),(direct),(not set),NaN
16,20210124,session_start,1113380.5608637494,9234249148,2021-01-24 19:24:43.623380+00:00,Oman,Muscat Governorate,mobile,(none),(direct),NaN,NaN
17,20210124,view_item,1118506.8087663530,1732296630,2021-01-24 21:40:08.966723+00:00,United States,Virginia,mobile,organic,google,(not set),NaN
18,20210124,session_start,1118506.8087663530,1732296630,2021-01-24 21:36:20.504510+00:00,United States,Virginia,mobile,organic,google,NaN,NaN
19,20210124,session_start,1133832.6128940177,7361961957,2021-01-24 14:06:27.043022+00:00,India,Maharashtra,desktop,<Other>,<Other>,NaN,NaN
20,20210124,session_start,1141870.1378316164,126234587,2021-01-24 10:02:45.823479+00:00,United States,Florida,mobile,<Other>,<Other>,NaN,NaN
21,20210124,session_start,1146020.0496105833,1092686103,2021-01-24 02:20:08.919302+00:00,Canada,Alberta,desktop,referral,shop.googlemerchandisestore.com,NaN,NaN
22,20210124,session_start,1149336.1597403620,9617391438,2021-01-24 08:36:19.926229+00:00,Australia,Queensland,desktop,(none),(direct),NaN,NaN
23,20210124,session_start,1152627.3131780848,2528075464,2021-01-24 17:33:59.739761+00:00,Israel,Center District,desktop,referral,<Other>,NaN,NaN
24,20210124,session_start,1161214.4824260456,3727317835,2021-01-24 23:01:54.876830+00:00,(not set),(not set),desktop,(none),(direct),NaN,NaN
25,20210124,session_start,1181313.0938779160,4590877971,2021-01-24 10:24:16.582803+00:00,France,Ile-de-France,mobile,(data deleted),(data deleted),NaN,NaN
26,20210124,view_item,1185870.3968802257,4764776796,2021-01-24 00:00:35.658608+00:00,United States,New York,desktop,(none),(direct),(not set),NaN
27,20210124,session_start,1185870.3968802257,4764776796,2021-01-24 00:00:30.039432+00:00,United States,New York,desktop,(none),(direct),NaN,NaN
28,20210124,session_start,1196138.8345831116,9302894959,2021-01-24 23:05:58.286301+00:00,Netherlands,North Holland,mobile,organic,google,NaN,NaN
29,20210124,view_item,1196138.8345831116,9302894959,2021-01-24 23:06:03.157996+00:00,Netherlands,North Holland,mobile,organic,google,(not set),NaN
30,20210124,session_start,1205136.8608351251,6378263811,2021-01-24 16:48:36.177758+00:00,United States,Pennsylvania,desktop,<Other>,<Other>,NaN,NaN
31,20210124,session_start,1208830.7589950936,663370232,2021-01-24 05:51:56.493330+00:00,Indonesia,(not set),desktop,organic,google,NaN,NaN
32,20210124,session_start,1218706.2717335074,4308459195,2021-01-24 10:34:29.177776+00:00,India,Maharashtra,mobile,<Other>,<Other>,NaN,NaN
33,20210124,session_start,1222085.2784427495,1069826008,2021-01-24 18:51:17.752178+00:00,United States,Tennessee,mobile,organic,google,NaN,NaN
34,20210124,session_start,1252002.8895484646,1110281686,2021-01-24 01:18:41.145016+00:00,United States,California,desktop,organic,google,NaN,NaN
35,20210124,session_start,1257778.0910586863,8411005740,2021-01-24 19:11:47.329420+00:00,United States,New York,mobile,organic,google,NaN,NaN
36,20210124,session_start,1259703.1800081340,6195411144,2021-01-24 12:18:30.165512+00:00,United States,California,tablet,organic,google,NaN,NaN
37,20210124,session_start,1260502.7253063162,5422754161,2021-01-24 15:19:26.787682+00:00,United States,California,mobile,organic,google,NaN,NaN
38,20210124,session_start,1260502.7253063162,4951569819,2021-01-24 23:42:49.508562+00:00,United States,California,mobile,(data deleted),(data deleted),NaN,NaN
39,20210124,session_start,1269832.1712479959,1188075785,2021-01-24 00:45:48.840087+00:00,United States,Tennessee,mobile,cpc,google,NaN,NaN

## Cleaning

In [6]:
# Format Date
df['event_date'] = pd.to_datetime(df['event_date'], format = '%Y%m%d')

In [7]:
# creating a unique session key
# session_id by itself is just time-based
df['session_key'] = df['user_pseudo_id'] + '-' + df['session_id'].astype(str)
df = df.drop(columns=['user_pseudo_id', 'session_id'])

In [8]:
# Dropping Duplicate events, if any
print(len(df))
df = df.drop_duplicates(subset= ['session_key','event_name','event_ts'])
print(len(df))

238073
238073

In [9]:
#Checking Missing Values
df.isna().sum()

event_date              0
event_name              0
event_ts                0
country                 0
state                   0
device_category         0
traffic_medium          0
traffic_source          0
transaction_id     116549
revenue            237169
session_key             0
dtype: int64

In [10]:
df.head(50)

,event_date,event_name,event_ts,country,state,device_category,traffic_medium,traffic_source,transaction_id,revenue,session_key
0,2021-01-01,session_start,2021-01-01 02:31:58.563156+00:00,France,Auvergne-Rhone-Alpes,desktop,organic,google,NaN,NaN,1003046.9452926974-3209612510
1,2021-01-01,view_item,2021-01-01 16:17:24.961359+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
2,2021-01-01,session_start,2021-01-01 16:15:31.708459+00:00,India,Maharashtra,mobile,<Other>,<Other>,NaN,NaN,1023282.4639847710-7473279052
3,2021-01-01,add_shipping_info,2021-01-01 16:26:27.293518+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
4,2021-01-01,view_item,2021-01-01 16:17:03.025952+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
5,2021-01-01,view_item,2021-01-01 16:25:20.637924+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
6,2021-01-01,add_shipping_info,2021-01-01 16:27:31.697610+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
7,2021-01-01,view_item,2021-01-01 16:24:46.227228+00:00,India,Maharashtra,mobile,<Other>,<Other>,(not set),NaN,1023282.4639847710-7473279052
8,2021-01-01,session_start,2021-01-01 15:48:32.499719+00:00,United States,Wisconsin,desktop,referral,<Other>,NaN,NaN,1026043.4481623879-5588834374
9,2021-01-01,session_start,2021-01-01 12:25:51.286460+00:00,United States,Wisconsin,desktop,cpc,google,NaN,NaN,1026043.4481623879-9083794581
10,2021-01-01,session_start,2021-01-01 11:27:32.334474+00:00,United States,Georgia,mobile,referral,<Other>,NaN,NaN,1026409.1551860912-1636061293
11,2021-01-01,session_start,2021-01-01 14:41:28.495200+00:00,United States,Georgia,mobile,(data deleted),(data deleted),NaN,NaN,1026409.1551860912-328130591
12,2021-01-01,session_start,2021-01-01 01:18:08.907142+00:00,Canada,Alberta,mobile,(none),(direct),NaN,NaN,1032138.1796039159-7352869284
13,2021-01-01,session_start,2021-01-01 21:30:27.941932+00:00,India,Rajasthan,mobile,<Other>,<Other>,NaN,NaN,1037928.9294661675-2214210438
14,2021-01-01,session_start,2021-01-01 07:39:56.294418+00:00,United States,Massachusetts,desktop,(none),(direct),NaN,NaN,1045950.7099606829-2961336242
15,2021-01-01,session_start,2021-01-01 14:09:40.700715+00:00,Bangladesh,(not set),desktop,referral,<Other>,NaN,NaN,1051288.9523352374-301526162
16,2021-01-01,session_start,2021-01-01 03:32:31.587116+00:00,United States,Massachusetts,mobile,<Other>,<Other>,NaN,NaN,1054372.6755770068-5017102538
17,2021-01-01,session_start,2021-01-01 16:07:02.788319+00:00,Kuwait,(not set),mobile,referral,<Other>,NaN,NaN,1064574.6224708641-8286443552
18,2021-01-01,session_start,2021-01-01 17:08:52.444301+00:00,Indonesia,Banten,desktop,organic,google,NaN,NaN,1066655.6240997015-4853714198
19,2021-01-01,session_start,2021-01-01 23:28:23.762831+00:00,Brazil,State of Parana,desktop,organic,google,NaN,NaN,1080064.0071613184-3437704805
20,2021-01-01,session_start,2021-01-01 21:45:01.332616+00:00,Canada,Quebec,desktop,referral,<Other>,NaN,NaN,1082746.7285674512-5036401017
21,2021-01-01,session_start,2021-01-01 07:47:35.084735+00:00,Greece,Attica,mobile,(none),(direct),NaN,NaN,1097358.9593491100-5513366801
22,2021-01-01,session_start,2021-01-01 15:41:16.836928+00:00,China,Guangdong Province,desktop,(none),(direct),NaN,NaN,1104313.9641823605-5509597950
23,2021-01-01,session_start,2021-01-01 12:46:31.191174+00:00,Canada,Ontario,mobile,organic,google,NaN,NaN,1107198.5152483918-7833645738
24,2021-01-01,add_shipping_info,2021-01-01 00:08:24.794041+00:00,India,Uttar Pradesh,desktop,(none),(direct),(not set),NaN,1112823.8475775772-4251926878
25,2021-01-01,add_shipping_info,2021-01-01 00:07:55.574192+00:00,India,Uttar Pradesh,desktop,(none),(direct),(not set),NaN,1112823.8475775772-4251926878
26,2021-01-01,add_shipping_info,2021-01-01 00:08:10.885964+00:00,India,Uttar Pradesh,desktop,(none),(direct),(not set),NaN,1112823.8475775772-4251926878
27,2021-01-01,add_shipping_info,2021-01-01 00:07:07.807393+00:00,India,Uttar Pradesh,desktop,(none),(direct),(not set),NaN,1112823.8475775772-4251926878
28,2021-01-01,view_item,2021-01-01 00:01:16.774207+00:00,India,Uttar Pradesh,desktop,(none),(direct),(not set),NaN,1112823.8475775772-4251926878
29,2021-01-01,session_start,2021-01-01 23:26:15.127001+00:00,United States,Oklahoma,mobile,organic,google,NaN,NaN,1116587.1725520171-7574595789
30,2021-01-01,session_start,2021-01-01 22:37:59.911144+00:00,Turkey,Istanbul,desktop,(none),(direct),NaN,NaN,1127824.3503063268-6303868874
31,2021-01-01,session_start,2021-01-01 23:48:15.241143+00:00,India,Madhya Pradesh,mobile,referral,<Other>,NaN,NaN,1134825.6533092350-8372021476
32,2021-01-01,session_start,2021-01-01 18:51:31.611025+00:00,Japan,Tokyo,mobile,<Other>,<Other>,NaN,NaN,1138692.0103796281-292439755
33,2021-01-01,view_item,2021-01-01 16:11:02.246454+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
34,2021-01-01,view_item,2021-01-01 16:22:43.485514+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
35,2021-01-01,view_item,2021-01-01 16:23:28.344003+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
36,2021-01-01,view_item,2021-01-01 16:13:12.635581+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
37,2021-01-01,view_item,2021-01-01 16:27:26.665929+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
38,2021-01-01,view_item,2021-01-01 16:00:36.388075+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
39,2021-01-01,view_item,2021-01-01 16:24:12.298380+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
40,2021-01-01,view_item,2021-01-01 16:04:31.488516+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
41,2021-01-01,view_item,2021-01-01 16:15:42.422150+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
42,2021-01-01,view_item,2021-01-01 16:10:02.388009+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
43,2021-01-01,view_item,2021-01-01 16:00:00.561862+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
44,2021-01-01,view_item,2021-01-01 16:08:21.362666+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
45,2021-01-01,view_item,2021-01-01 16:05:58.610868+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
46,2021-01-01,view_item,2021-01-01 16:02:33.978213+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
47,2021-01-01,view_item,2021-01-01 16:06:38.866709+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
48,2021-01-01,add_shipping_info,2021-01-01 16:38:52.936998+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775
49,2021-01-01,view_item,2021-01-01 16:10:36.954180+00:00,Portugal,(not set),desktop,(none),(direct),(not set),NaN,1160488.2375923167-2309154775

In [267]:
# 2. Get unique values 
for c in ['traffic_source','traffic_medium','device_category']:
    print(c)
    print(df[c].unique().tolist())

traffic_source
['google', 'shop.googlemerchandisestore.com', '(direct)', '<Other>', '(data deleted)']
traffic_medium
['organic', 'referral', '(none)', '<Other>', 'cpc', '(data deleted)']
device_category
['mobile', 'desktop', 'tablet']

In [20]:
# defining channel names
def channel(row):
    src = row['traffic_source']
    med = row['traffic_medium']

    if src == 'shop.googlemerchandisestore.com':
        return 'Unattributed'
    if med == 'organic':
        return 'Organic Search'
    if med == 'cpc':
        return 'Paid Search'
    if med == 'referral':
        return 'Referral'
    if src == '(direct)':
        return 'Direct'
    if '(data deleted)' in (src, med):
        return 'Unattributed'
    return 'Unattributed'

df['channel'] = df.apply(channel, axis=1)

### Funnel Data Prep

In [21]:
FUNNEL_STEPS = [
    'session_start',
    'view_item',
    'add_to_cart',
    'begin_checkout',
    'add_shipping_info',
    'add_payment_info',
    'purchase',
]
LABELS = {
    'session_start': 'Session',
    'view_item': 'Product View',
    'add_to_cart': 'Add to Cart',
    'begin_checkout': 'Checkout Started',
    'add_shipping_info': 'Shipping Info',
    'add_payment_info': 'Payment Info',
    'purchase': 'Purchase',
}

STEP_ORDER = {
    'session_start': 1,
    'view_item': 2,
    'add_to_cart': 3,
    'begin_checkout': 4,
    'add_shipping_info': 5,
    'add_payment_info': 6,
    'purchase': 7,
}

In [22]:
df['step'] = df['event_name'].map(LABELS)
df['step_order'] = df['event_name'].map(STEP_ORDER)

In [23]:
# Aggregating funnel data. 
funnel = df.groupby(['event_date','device_category','step','step_order'])['session_key'].nunique().reset_index(name = 'sessions')

In [24]:
#Check
funnel.groupby('step_order')['sessions'].sum()

step_order
1    116514
2     23153
3      4548
4      2161
5      2161
6      1563
7      1116
Name: sessions, dtype: int64

### Purchase Data Prep

In [25]:
# Aggregating purchase data
purchases = df[df['event_name'] == 'purchase'].drop_duplicates(subset= ['transaction_id','session_key'])
pur_df = purchases.groupby(['event_date','country','device_category','channel'])['revenue'].sum().reset_index()

In [26]:
purchases.head(5)

,event_date,event_name,event_ts,country,state,device_category,traffic_medium,traffic_source,transaction_id,revenue,session_key,channel,step,step_order
2840,2021-01-01,purchase,2021-01-01 18:47:04.715080+00:00,(not set),(not set),mobile,organic,google,887131,22.0,3351786.5083077372-8044807491,Organic Search,Purchase,7
2898,2021-01-01,purchase,2021-01-01 03:29:50.052499+00:00,Israel,Center District,mobile,(none),(direct),722217,20.0,40650638.8176789956-3410418880,Direct,Purchase,7
2934,2021-01-01,purchase,2021-01-01 04:55:33.799172+00:00,United States,Indiana,desktop,(data deleted),(data deleted),146188,14.0,87047667.1042912591-5358392223,Unattributed,Purchase,7
2937,2021-01-01,purchase,2021-01-01 04:49:56.446915+00:00,United States,Indiana,desktop,(data deleted),(data deleted),966325,44.0,87047667.1042912591-5358392223,Unattributed,Purchase,7
2963,2021-01-01,purchase,2021-01-01 05:53:02.021197+00:00,India,Karnataka,mobile,(none),(direct),479241,52.0,68546038.8820428933-5425867143,Direct,Purchase,7

### Export

In [27]:
# Save to CSV
funnel.to_csv('Funnel.csv', index=False)
pur_df.to_csv('Purchases.csv',index=False)